project_id = "zvxcwwhsjtdliihlvvof"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.test-integration]
verify_jwt = false

[functions.check-integration]
verify_jwt = false

[functions.save-integration]
verify_jwt = false

[functions.process-document]
verify_jwt = false