project_id = "zvxcwwhsjtdliihlvvof"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.test-integration]
verify_jwt = false

[functions.check-integration]
verify_jwt = false

[functions.save-integration]
verify_jwt = false

[functions.fetch-erp-clients]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.save-whatsapp-config]
verify_jwt = false

[functions.test-whatsapp-connection]
verify_jwt = false
