// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvxcwwhsjtdliihlvvof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2eGN3d2hzanRkbGlpaGx2dm9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1OTU5NDIsImV4cCI6MjA4NDE3MTk0Mn0.cAG6WRnoE0QkJwGdkiA9dZ2pBHWXenxsH87ThKvH61k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});